spring:
  application:
    name: order-service
    
#server:
#  port: 8201

  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream   
        
        
item-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
    
#ribbon通用配置      
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  


      
      
---
spring:
  profiles: order1
  
server:
  port: 8201
---
spring:
  profiles: order2
  
server:
  port: 8202